[package]
name = "editor-plugin-host"

[package.edition]
workspace = true

[package.version]
workspace = true

[package.license]
workspace = true

[package.rust-version]
workspace = true

[dependencies.editor-core]
path = "../editor-core"

[dependencies.editor-path]
path = "../editor-path"

[dependencies.editor-plugin-api]
path = "../../user/sdk"

[lib]
path = "src/lib.rs"
name = "editor_plugin_host"
required-features = []
crate-type = ["lib"]
