[package]
name = "editor-fs"

[package.edition]
workspace = true

[package.version]
workspace = true

[package.license]
workspace = true

[package.rust-version]
workspace = true

[dependencies]
serde_json = "1.0.149"

[dependencies.editor-plugin-api]
path = "../../user/sdk"
features = ["test-helpers"]

[lib]
path = "src/lib.rs"
name = "editor_fs"
required-features = []
crate-type = ["lib"]

[lints]
workspace = true
