[package]
name = "editor-icons"
build = "build.rs"

[package.edition]
workspace = true

[package.version]
workspace = true

[package.license]
workspace = true

[package.rust-version]
workspace = true

[build-dependencies]

[lib]
path = "src/lib.rs"
name = "editor_icons"
required-features = []
crate-type = ["lib"]
