[package]
name = "editor-icons"

[package.edition]
workspace = true

[package.version]
workspace = true

[package.license]
workspace = true

[package.rust-version]
workspace = true

[dependencies.editor-plugin-api]
path = "../../user/sdk"

[lib]
path = "src/lib.rs"
name = "editor_icons"
required-features = []
crate-type = ["lib"]

[lints]
workspace = true
