id = "gruvbox-light"
name = "Gruvbox Light"

[tokens]
"ui.background" = "#fbf1c7"
"ui.foreground" = "#3c3836"
"ui.cursor" = "#6eaaff"
"ui.selection" = "#374763"
"ui.picker.highlight" = "#076678"
"ui.input.background" = "#fbf1c7"
"ui.input.foreground" = "#3c3836"
"ui.autocomplete.background" = "#e9dfb5"
"ui.autocomplete.foreground" = "#3c3836"
"ui.autocomplete.muted" = "#8c8570"
"ui.autocomplete.border" = "#ddd3a9"
"ui.autocomplete.selection" = "#e1d7ad"
"ui.autocomplete.documentation.background" = "#e5dbb1"
"ui.hover.background" = "#e9dfb5"
"ui.hover.foreground" = "#3c3836"
"ui.hover.muted" = "#8c8570"
"ui.hover.border" = "#ddd3a9"
"ui.hover.focused.border" = "#cbc197"
"ui.hover.header.background" = "#e3d9af"
"ui.hover.selection" = "#dbd1a7"
"ui.yank-flash" = "#4585886e"
"ui.statusline.active" = "#076678"
"ui.statusline.inactive" = "#928374"
"ui.notification.background" = "#e9dfb5"
"ui.notification.foreground" = "#3c3836"
"ui.notification.title" = "#3c3836"
"ui.notification.muted" = "#8c8570"
"ui.notification.border" = "#ddd3a9"
"ui.notification.progress.background" = "#dbd1a7"
"ui.notification.progress.fill" = "#076678"
"ui.notification.info" = "#076678"
"ui.notification.success" = "#79740e"
"ui.notification.warning" = "#b57614"
"ui.notification.error" = "#cc241d"
# Git status
"git.status.section.header" = "#b57614"
"git.status.section.count" = "#928374"
"git.status.header.label" = "#076678"
"git.status.header.value" = "#79740e"
"git.status.header.hash" = "#928374"
"git.status.header.summary" = "#3c3836"
"git.status.in-progress" = "#427b58"
"git.status.entry.added" = "#79740e"
"git.status.entry.modified" = "#b57614"
"git.status.entry.deleted" = "#af3a03"
"git.status.entry.renamed" = "#8f3f71"
"git.status.entry.copied" = "#427b58"
"git.status.entry.updated" = "#076678"
"git.status.entry.changed" = "#79740e"
"git.status.entry.untracked" = "#af3a03"
"git.status.entry.path" = "#3c3836"
"git.status.commit.hash" = "#928374"
"git.status.commit.summary" = "#3c3836"
"git.status.stash.name" = "#b57614"
"git.status.stash.summary" = "#3c3836"
"git.status.command" = "#076678"
"git.status.message" = "#928374"
# Git fringe
"git.fringe.added" = "#79740e"
"git.fringe.modified" = "#b57614"
"git.fringe.removed" = "#af3a03"
"syntax.attribute" = "#076678"
"syntax.comment" = "#928374"
"syntax.constant" = "#b57614"
"syntax.constant.builtin" = "#b57614"
"syntax.constructor" = "#8f3f71"
"syntax.function" = "#076678"
"syntax.function.macro" = "#af3a03"
"syntax.keyword" = "#af3a03"
"syntax.label" = "#af3a03"
"syntax.module" = "#79740e"
"syntax.operator" = "#af3a03"
"syntax.property" = "#b57614"
"syntax.punctuation.bracket" = "#3c3836"
"syntax.punctuation.delimiter" = "#3c3836"
"syntax.string" = "#79740e"
"syntax.type" = "#427b58"
"syntax.type.builtin" = "#427b58"
"syntax.variable" = "#3c3836"
"syntax.variable.builtin" = "#8f3f71"
"syntax.none" = "#00000000"
"syntax.preproc" = "#076678"
"syntax.define" = "#076678"
"syntax.punctuation.special" = "#3c3836"
"syntax.string.regex" = "#79740e"
"syntax.string.regexp" = "#79740e"
"syntax.string.escape" = "#79740e"
"syntax.string.special" = "#79740e"
"syntax.string.special.path" = "#79740e"
"syntax.string.special.symbol" = "#3c3836"
"syntax.string.special.url" = "#79740e"
"syntax.character" = "#79740e"
"syntax.character.special" = "#79740e"
"syntax.boolean" = "#b57614"
"syntax.number" = "#b57614"
"syntax.number.float" = "#b57614"
"syntax.float" = "#b57614"
"syntax.function.builtin" = "#076678"
"syntax.function.call" = "#076678"
"syntax.function.method" = "#076678"
"syntax.method" = "#076678"
"syntax.method.call" = "#076678"
"syntax.parameter" = "#3c3836"
"syntax.keyword.conditional" = "#af3a03"
"syntax.keyword.debug" = "#af3a03"
"syntax.keyword.directive" = "#076678"
"syntax.keyword.directive.define" = "#076678"
"syntax.keyword.exception" = "#af3a03"
"syntax.keyword.function" = "#af3a03"
"syntax.keyword.import" = "#af3a03"
"syntax.keyword.operator" = "#af3a03"
"syntax.keyword.repeat" = "#af3a03"
"syntax.keyword.return" = "#af3a03"
"syntax.keyword.storage" = "#427b58"
"syntax.conditional" = "#af3a03"
"syntax.repeat" = "#af3a03"
"syntax.debug" = "#af3a03"
"syntax.include" = "#af3a03"
"syntax.exception" = "#af3a03"
"syntax.type.definition" = "#427b58"
"syntax.type.qualifier" = "#427b58"
"syntax.storageclass" = "#427b58"
"syntax.field" = "#b57614"
"syntax.variable.member" = "#b57614"
"syntax.variable.parameter" = "#3c3836"
"syntax.constant.macro" = "#af3a03"
"syntax.markup" = "#3c3836"
"syntax.markup.strong" = "#427b58"
"syntax.markup.italic" = "#af3a03"
"syntax.markup.underline" = "#79740e"
"syntax.markup.strikethrough" = "#928374"
"syntax.markup.heading" = "#af3a03"
"syntax.markup.raw" = "#79740e"
"syntax.markup.math" = "#af3a03"
"syntax.markup.environment" = "#af3a03"
"syntax.markup.environment.name" = "#427b58"
"syntax.markup.link" = "#79740e"
"syntax.markup.link.label" = "#3c3836"
"syntax.markup.list" = "#3c3836"
"syntax.markup.list.checked" = "#79740e"
"syntax.markup.list.unchecked" = "#928374"
"syntax.comment.todo" = "#79740e"
"syntax.comment.note" = "#af3a03"
"syntax.comment.warning" = "#b57614"
"syntax.comment.error" = "#af3a03"
"syntax.diff.plus" = "#79740e"
"syntax.diff.minus" = "#af3a03"
"syntax.diff.delta" = "#b57614"
"syntax.namespace" = "#79740e"
"syntax.symbol" = "#3c3836"
"syntax.text" = "#3c3836"
"syntax.text.strong" = "#427b58"
"syntax.text.emphasis" = "#af3a03"
"syntax.text.underline" = "#79740e"
"syntax.text.strike" = "#928374"
"syntax.text.title" = "#af3a03"
"syntax.text.literal" = "#79740e"
"syntax.text.uri" = "#79740e"
"syntax.text.math" = "#af3a03"
"syntax.text.environment" = "#af3a03"
"syntax.text.environment.name" = "#427b58"
"syntax.text.reference" = "#3c3836"
"syntax.text.todo" = "#79740e"
"syntax.text.todo.checked" = "#79740e"
"syntax.text.todo.unchecked" = "#928374"
"syntax.text.note" = "#af3a03"
"syntax.text.note.comment" = "#af3a03"
"syntax.text.warning" = "#b57614"
"syntax.text.danger" = "#af3a03"
"syntax.text.danger.comment" = "#af3a03"
"syntax.text.diff.add" = "#79740e"
"syntax.text.diff.delete" = "#af3a03"
"syntax.tag" = "#af3a03"
"syntax.tag.attribute" = "#076678"
"syntax.tag.delimiter" = "#3c3836"
"syntax.punctuation" = "#3c3836"
"syntax.macro" = "#af3a03"
"syntax.structure" = "#427b58"
"syntax.lsp.type.class" = "#427b58"
"syntax.lsp.type.comment" = "#928374"
"syntax.lsp.type.decorator" = "#af3a03"
"syntax.lsp.type.enum" = "#427b58"
"syntax.lsp.type.enumMember" = "#b57614"
"syntax.lsp.type.function" = "#076678"
"syntax.lsp.type.interface" = "#8f3f71"
"syntax.lsp.type.macro" = "#af3a03"
"syntax.lsp.type.method" = "#076678"
"syntax.lsp.type.modifier.java" = "#af3a03"
"syntax.lsp.type.namespace" = "#79740e"
"syntax.lsp.type.parameter" = "#3c3836"
"syntax.lsp.type.property" = "#b57614"
"syntax.lsp.type.struct" = "#427b58"
"syntax.lsp.type.type" = "#427b58"
"syntax.lsp.type.typeParameter" = "#427b58"
"syntax.lsp.type.variable" = "#3c3836"

[options]
"ui.line-number.relative" = true
font = "default"
font_size = 18
cursor_roundness = 2
picker_roundness = 16

[langs.rust]
indent = 4
format_on_save = true
use_tabs = false

[langs.markdown]
indent = 0
format_on_save = false
use_tabs = false
