[package]
name = "editor-dap"

[package.edition]
workspace = true

[package.version]
workspace = true

[package.license]
workspace = true

[package.rust-version]
workspace = true

[dependencies.editor-jobs]
path = "../editor-jobs"

[lib]
path = "src/lib.rs"
name = "editor_dap"
required-features = []
crate-type = ["lib"]
