[package]
name = "editor-dap"

[package.edition]
workspace = true

[package.version]
workspace = true

[package.license]
workspace = true

[package.rust-version]
workspace = true

[dependencies]
dap-types = "0.0.1"
serde = "1.0.228"
serde_json = "1.0.149"

[dependencies.editor-jobs]
path = "../editor-jobs"

[dependencies.editor-tool-install]
path = "../editor-tool-install"

[lib]
path = "src/lib.rs"
name = "editor_dap"
required-features = []
crate-type = ["lib"]
