[package]
name = "volt"
build = "build.rs"

[package.edition]
workspace = true

[package.version]
workspace = true

[package.license]
workspace = true

[package.rust-version]
workspace = true

[dependencies]
abi_stable = "0.11"
sysinfo = "0.37.2"

[dependencies.editor-buffer]
path = "../editor-buffer"

[dependencies.editor-core]
path = "../editor-core"

[dependencies.editor-dap]
path = "../editor-dap"

[dependencies.editor-fs]
path = "../editor-fs"

[dependencies.editor-git]
path = "../editor-git"

[dependencies.editor-icons]
path = "../editor-icons"

[dependencies.editor-jobs]
path = "../editor-jobs"

[dependencies.editor-lsp]
path = "../editor-lsp"

[dependencies.editor-picker]
path = "../editor-picker"

[dependencies.editor-plugin-api]
path = "../../user/sdk"

[dependencies.editor-plugin-host]
path = "../editor-plugin-host"

[dependencies.editor-sdl]
path = "../editor-sdl"

[dependencies.editor-syntax]
path = "../editor-syntax"

[dependencies.editor-terminal]
path = "../editor-terminal"

[dependencies.editor-theme]
path = "../editor-theme"

[dependencies.user]
path = "../../user"
package = "volt-user"

[dev-dependencies]
toml = "0.8.23"

[build-dependencies]
toml = "0.8.23"

[target."cfg(unix)".dependencies.rustix]
version = "1.1.4"
features = ["process"]

[target."cfg(unix)".dev-dependencies]

[target."cfg(unix)".build-dependencies]

[target."cfg(windows)".dependencies]

[target."cfg(windows)".dev-dependencies]

[target."cfg(windows)".build-dependencies]
embed-resource = "2.5.1"

[[bin]]
path = "src/main.rs"
name = "volt"
required-features = []
