[options]
"ui.line-number.relative" = true
scrolloff = 5
font = "Liga Berkeley Mono"
font_size = 20
cursor_roundness = 2
picker_roundness = 16
"window.opacity" = 0.1
"window.blur" = 1.0

[langs.rust]
indent = 4
format_on_save = false
use_tabs = false

[langs.c]
indent = 4
format_on_save = true
use_tabs = false

[langs.cpp]
indent = 4
format_on_save = true
use_tabs = false

[langs.csharp]
indent = 4
format_on_save = true
use_tabs = false

[langs.css]
indent = 2
format_on_save = false
use_tabs = false

[langs.gitcommit]
indent = 4
format_on_save = false
use_tabs = false

[langs.go]
indent = 4
format_on_save = true
use_tabs = false

[langs.html]
indent = 2
format_on_save = false
use_tabs = false

[langs.javascript]
indent = 2
format_on_save = false
use_tabs = false

[langs.jsx]
indent = 2
format_on_save = false
use_tabs = false

[langs.json]
indent = 2
format_on_save = false
use_tabs = false

[langs.make]
indent = 4
format_on_save = false
use_tabs = true

[langs.markdown]
indent = 0
format_on_save = false
use_tabs = false

[langs.odin]
indent = 4
format_on_save = true
use_tabs = false

[langs.python]
indent = 4
format_on_save = true
use_tabs = false

[langs.scss]
indent = 2
format_on_save = false
use_tabs = false

[langs.sql]
indent = 2
format_on_save = false
use_tabs = false

[langs.typescript]
indent = 2
format_on_save = false
use_tabs = false

[langs.tsx]
indent = 2
format_on_save = false
use_tabs = false

[langs.toml]
indent = 4
format_on_save = false
use_tabs = false

[langs.yaml]
indent = 2
format_on_save = false
use_tabs = false

[langs.zig]
indent = 4
format_on_save = true
use_tabs = false

[langs.bash]
indent = 4
format_on_save = false
use_tabs = false

[langs.clojure]
indent = 2
format_on_save = false
use_tabs = false

[langs.cmake]
indent = 2
format_on_save = false
use_tabs = false

[langs.elixir]
indent = 2
format_on_save = false
use_tabs = false

[langs.graphql]
indent = 2
format_on_save = false
use_tabs = false

[langs.hcl]
indent = 2
format_on_save = false
use_tabs = false

[langs.java]
indent = 4
format_on_save = false
use_tabs = false

[langs.kotlin]
indent = 4
format_on_save = false
use_tabs = false

[langs.latex]
indent = 2
format_on_save = false
use_tabs = false

[langs.lua]
indent = 4
format_on_save = false
use_tabs = false

[langs.nix]
indent = 2
format_on_save = false
use_tabs = false

[langs.perl]
indent = 4
format_on_save = false
use_tabs = false

[langs.php]
indent = 4
format_on_save = false
use_tabs = false

[langs.proto]
indent = 2
format_on_save = false
use_tabs = false

[langs.r]
indent = 2
format_on_save = false
use_tabs = false

[langs.ruby]
indent = 2
format_on_save = false
use_tabs = false

[langs.scala]
indent = 2
format_on_save = false
use_tabs = false

[langs.solidity]
indent = 4
format_on_save = false
use_tabs = false

[langs.swift]
indent = 4
format_on_save = false
use_tabs = false

[langs.vim]
indent = 2
format_on_save = false
use_tabs = false

[langs.xml]
indent = 2
format_on_save = false
use_tabs = false
