id = "gruvbox-dark"
name = "Gruvbox Dark"

[tokens]
"ui.background" = "#181818"
"ui.foreground" = "#ebdbb2"
"ui.cursor" = "#f9f9f9"
"ui.selection" = "#4e4743"
"ui.picker.highlight" = "#83a598"
"ui.input.background" = "#181818"
"ui.input.foreground" = "#ebdbb2"
"ui.autocomplete.background" = "#282828"
"ui.autocomplete.foreground" = "#ebdbb2"
"ui.autocomplete.muted" = "#9a917b"
"ui.autocomplete.border" = "#464646"
"ui.autocomplete.selection" = "#424242"
"ui.autocomplete.documentation.background" = "#3e3e3e"
"ui.hover.background" = "#282828"
"ui.hover.foreground" = "#ebdbb2"
"ui.hover.muted" = "#9a917b"
"ui.hover.border" = "#464646"
"ui.hover.focused.border" = "#585858"
"ui.hover.header.background" = "#404040"
"ui.hover.selection" = "#484848"
"ui.yank-flash" = "#83a5986e"
"ui.statusline.active" = "#83a598"
"ui.statusline.inactive" = "#928374"
"ui.notification.background" = "#282828"
"ui.notification.foreground" = "#ebdbb2"
"ui.notification.title" = "#ebdbb2"
"ui.notification.muted" = "#9a917b"
"ui.notification.border" = "#464646"
"ui.notification.progress.background" = "#404040"
"ui.notification.progress.fill" = "#83a598"
"ui.notification.info" = "#83a598"
"ui.notification.success" = "#b8bb26"
"ui.notification.warning" = "#fabd2f"
"ui.notification.error" = "#fb4934"
# Git status
"git.status.section.header" = "#fe8019"
"git.status.section.count" = "#928374"
"git.status.header.label" = "#83a598"
"git.status.header.value" = "#fabd2f"
"git.status.header.hash" = "#928374"
"git.status.header.summary" = "#ebdbb2"
"git.status.in-progress" = "#8ec07c"
"git.status.entry.added" = "#b8bb26"
"git.status.entry.modified" = "#fe8019"
"git.status.entry.deleted" = "#fb4934"
"git.status.entry.renamed" = "#d3869b"
"git.status.entry.copied" = "#8ec07c"
"git.status.entry.updated" = "#83a598"
"git.status.entry.changed" = "#fabd2f"
"git.status.entry.untracked" = "#fb4934"
"git.status.entry.path" = "#ebdbb2"
"git.status.commit.hash" = "#928374"
"git.status.commit.summary" = "#ebdbb2"
"git.status.stash.name" = "#fe8019"
"git.status.stash.summary" = "#ebdbb2"
"git.status.command" = "#83a598"
"git.status.message" = "#928374"
# Git fringe
"git.fringe.added" = "#b8bb26"
"git.fringe.modified" = "#fe8019"
"git.fringe.removed" = "#fb4934"
"syntax.attribute" = "#83a598"
"syntax.comment" = "#928374"
"syntax.constant" = "#d3869b"
"syntax.constant.builtin" = "#d3869b"
"syntax.constructor" = "#8ec07c"
"syntax.function" = "#fabd2f"
"syntax.function.macro" = "#fe8019"
"syntax.keyword" = "#fabd2f"
"syntax.label" = "#fb4934"
"syntax.module" = "#b8bb26"
"syntax.operator" = "#fe8019"
"syntax.property" = "#8ec07c"
"syntax.punctuation.bracket" = "#ebdbb2"
"syntax.punctuation.delimiter" = "#ebdbb2"
"syntax.string" = "#98971a"
"syntax.type" = "#8ec07c"
"syntax.type.builtin" = "#8ec07c"
"syntax.variable" = "#ebdbb2"
"syntax.variable.builtin" = "#d3869b"
"syntax.none" = "#00000000"
"syntax.preproc" = "#83a598"
"syntax.define" = "#83a598"
"syntax.punctuation.special" = "#ebdbb2"
"syntax.string.regex" = "#b8bb26"
"syntax.string.regexp" = "#b8bb26"
"syntax.string.escape" = "#b8bb26"
"syntax.string.special" = "#b8bb26"
"syntax.string.special.path" = "#b8bb26"
"syntax.string.special.symbol" = "#ebdbb2"
"syntax.string.special.url" = "#b8bb26"
"syntax.character" = "#b8bb26"
"syntax.character.special" = "#b8bb26"
"syntax.boolean" = "#d3869b"
"syntax.number" = "#d3869b"
"syntax.number.float" = "#d3869b"
"syntax.float" = "#d3869b"
"syntax.function.builtin" = "#fabd2f"
"syntax.function.call" = "#fabd2f"
"syntax.function.method" = "#fabd2f"
"syntax.method" = "#fabd2f"
"syntax.method.call" = "#fabd2f"
"syntax.parameter" = "#ebdbb2"
"syntax.keyword.conditional" = "#fb4934"
"syntax.keyword.debug" = "#fb4934"
"syntax.keyword.directive" = "#83a598"
"syntax.keyword.directive.define" = "#83a598"
"syntax.keyword.exception" = "#fb4934"
"syntax.keyword.function" = "#fb4934"
"syntax.keyword.import" = "#fb4934"
"syntax.keyword.operator" = "#fe8019"
"syntax.keyword.repeat" = "#fb4934"
"syntax.keyword.return" = "#fb4934"
"syntax.keyword.storage" = "#8ec07c"
"syntax.conditional" = "#fb4934"
"syntax.repeat" = "#fb4934"
"syntax.debug" = "#fb4934"
"syntax.include" = "#fb4934"
"syntax.exception" = "#fb4934"
"syntax.type.definition" = "#8ec07c"
"syntax.type.qualifier" = "#8ec07c"
"syntax.storageclass" = "#8ec07c"
"syntax.field" = "#8ec07c"
"syntax.variable.member" = "#8ec07c"
"syntax.variable.parameter" = "#ebdbb2"
"syntax.constant.macro" = "#fe8019"
"syntax.markup" = "#ebdbb2"
"syntax.markup.strong" = "#8ec07c"
"syntax.markup.italic" = "#fb4934"
"syntax.markup.underline" = "#b8bb26"
"syntax.markup.strikethrough" = "#928374"
"syntax.markup.heading" = "#fb4934"
"syntax.markup.raw" = "#b8bb26"
"syntax.markup.math" = "#fe8019"
"syntax.markup.environment" = "#fe8019"
"syntax.markup.environment.name" = "#8ec07c"
"syntax.markup.link" = "#b8bb26"
"syntax.markup.link.label" = "#ebdbb2"
"syntax.markup.list" = "#ebdbb2"
"syntax.markup.list.checked" = "#b8bb26"
"syntax.markup.list.unchecked" = "#928374"
"syntax.comment.todo" = "#fabd2f"
"syntax.comment.note" = "#fb4934"
"syntax.comment.warning" = "#fe8019"
"syntax.comment.error" = "#fb4934"
"syntax.diff.plus" = "#b8bb26"
"syntax.diff.minus" = "#fb4934"
"syntax.diff.delta" = "#fe8019"
"syntax.namespace" = "#b8bb26"
"syntax.symbol" = "#ebdbb2"
"syntax.text" = "#ebdbb2"
"syntax.text.strong" = "#8ec07c"
"syntax.text.emphasis" = "#fb4934"
"syntax.text.underline" = "#b8bb26"
"syntax.text.strike" = "#928374"
"syntax.text.title" = "#fb4934"
"syntax.text.literal" = "#b8bb26"
"syntax.text.uri" = "#b8bb26"
"syntax.text.math" = "#fe8019"
"syntax.text.environment" = "#fe8019"
"syntax.text.environment.name" = "#8ec07c"
"syntax.text.reference" = "#ebdbb2"
"syntax.text.todo" = "#fabd2f"
"syntax.text.todo.checked" = "#b8bb26"
"syntax.text.todo.unchecked" = "#928374"
"syntax.text.note" = "#fb4934"
"syntax.text.note.comment" = "#fb4934"
"syntax.text.warning" = "#fe8019"
"syntax.text.danger" = "#fb4934"
"syntax.text.danger.comment" = "#fb4934"
"syntax.text.diff.add" = "#b8bb26"
"syntax.text.diff.delete" = "#fb4934"
"syntax.tag" = "#fb4934"
"syntax.tag.attribute" = "#83a598"
"syntax.tag.delimiter" = "#ebdbb2"
"syntax.punctuation" = "#ebdbb2"
"syntax.macro" = "#fe8019"
"syntax.structure" = "#8ec07c"
"syntax.lsp.type.class" = "#8ec07c"
"syntax.lsp.type.comment" = "#928374"
"syntax.lsp.type.decorator" = "#fe8019"
"syntax.lsp.type.enum" = "#8ec07c"
"syntax.lsp.type.enumMember" = "#d3869b"
"syntax.lsp.type.function" = "#fabd2f"
"syntax.lsp.type.interface" = "#8ec07c"
"syntax.lsp.type.macro" = "#fe8019"
"syntax.lsp.type.method" = "#fabd2f"
"syntax.lsp.type.modifier.java" = "#fb4934"
"syntax.lsp.type.namespace" = "#b8bb26"
"syntax.lsp.type.parameter" = "#ebdbb2"
"syntax.lsp.type.property" = "#8ec07c"
"syntax.lsp.type.struct" = "#8ec07c"
"syntax.lsp.type.type" = "#8ec07c"
"syntax.lsp.type.typeParameter" = "#8ec07c"
"syntax.lsp.type.variable" = "#ebdbb2"

[options]
"ui.line-number.relative" = true
font = "default"
font_size = 18
cursor_roundness = 2
picker_roundness = 16

[langs.rust]
indent = 4
format_on_save = true
use_tabs = false

[langs.markdown]
indent = 0
format_on_save = false
use_tabs = false
