id = "gruvbox-dark"
name = "Gruvbox Dark"


[pallet]
background = "#101010"
surface = "#282828"
surface-muted = "#3e3e3e"
surface-header = "#404040"
surface-selection = "#424242"
surface-hover-selection = "#484848"
border = "#464646"
border-strong = "#585858"
selection = "#4e4743"
foreground = "#ebdbb2"
foreground-muted = "#9a917b"
foreground-subtle = "#928374"
cursor = "#f9f9f9"
blue = "#83a598"
blue-overlay = "#83a5986e"
green = "#b8bb26"
green-dark = "#98971a"
yellow = "#fabd2f"
red = "#fb4934"
orange = "#fe8019"
aqua = "#8ec07c"
purple = "#d3869b"
transparent = "#00000000"

[tokens]
"ui.background" = "pallet.background"
"ui.foreground" = "pallet.foreground"
"ui.cursor" = "pallet.cursor"
"ui.selection" = "pallet.selection"
"ui.picker.highlight" = "pallet.blue"
"ui.input.background" = "pallet.background"
"ui.input.foreground" = "pallet.foreground"
"ui.autocomplete.background" = "pallet.surface"
"ui.autocomplete.foreground" = "pallet.foreground"
"ui.autocomplete.muted" = "pallet.foreground-muted"
"ui.autocomplete.border" = "pallet.border"
"ui.autocomplete.selection" = "pallet.surface-selection"
"ui.autocomplete.documentation.background" = "pallet.surface-muted"
"ui.hover.background" = "pallet.surface"
"ui.hover.foreground" = "pallet.foreground"
"ui.hover.muted" = "pallet.foreground-muted"
"ui.hover.border" = "pallet.border"
"ui.hover.focused.border" = "pallet.border-strong"
"ui.hover.header.background" = "pallet.surface-header"
"ui.hover.selection" = "pallet.surface-hover-selection"
"ui.yank-flash" = "pallet.blue-overlay"
"ui.statusline.active" = "pallet.blue"
"ui.statusline.inactive" = "pallet.foreground-subtle"
"ui.notification.background" = "pallet.surface"
"ui.notification.foreground" = "pallet.foreground"
"ui.notification.title" = "pallet.foreground"
"ui.notification.muted" = "pallet.foreground-muted"
"ui.notification.border" = "pallet.border"
"ui.notification.progress.background" = "pallet.surface-header"
"ui.notification.progress.fill" = "pallet.blue"
"ui.notification.info" = "pallet.blue"
"ui.notification.success" = "pallet.green"
"ui.notification.warning" = "pallet.yellow"
"ui.notification.error" = "pallet.red"
# Git status
"git.status.section.header" = "pallet.orange"
"git.status.section.count" = "pallet.foreground-subtle"
"git.status.header.label" = "pallet.blue"
"git.status.header.value" = "pallet.yellow"
"git.status.header.hash" = "pallet.foreground-subtle"
"git.status.header.summary" = "pallet.foreground"
"git.status.in-progress" = "pallet.aqua"
"git.status.entry.added" = "pallet.green"
"git.status.entry.modified" = "pallet.orange"
"git.status.entry.deleted" = "pallet.red"
"git.status.entry.renamed" = "pallet.purple"
"git.status.entry.copied" = "pallet.aqua"
"git.status.entry.updated" = "pallet.blue"
"git.status.entry.changed" = "pallet.yellow"
"git.status.entry.untracked" = "pallet.red"
"git.status.entry.path" = "pallet.foreground"
"git.status.commit.hash" = "pallet.foreground-subtle"
"git.status.commit.summary" = "pallet.foreground"
"git.status.stash.name" = "pallet.orange"
"git.status.stash.summary" = "pallet.foreground"
"git.status.command" = "pallet.blue"
"git.status.message" = "pallet.foreground-subtle"
# Git fringe
"git.fringe.added" = "pallet.green"
"git.fringe.modified" = "pallet.orange"
"git.fringe.removed" = "pallet.red"
"syntax.attribute" = "pallet.blue"
"syntax.comment" = "pallet.foreground-subtle"
"syntax.constant" = "pallet.purple"
"syntax.constant.builtin" = "pallet.purple"
"syntax.constructor" = "pallet.aqua"
"syntax.function" = "pallet.blue"
"syntax.function.macro" = "pallet.orange"
"syntax.keyword" = "pallet.yellow"
"syntax.label" = "pallet.red"
"syntax.module" = "pallet.green"
"syntax.operator" = "pallet.orange"
"syntax.property" = "pallet.purple"
"syntax.punctuation.bracket" = "pallet.foreground"
"syntax.punctuation.delimiter" = "pallet.foreground"
"syntax.string" = "pallet.green-dark"
"syntax.type" = "pallet.aqua"
"syntax.type.builtin" = "pallet.aqua"
"syntax.variable" = "pallet.foreground"
"syntax.variable.builtin" = "pallet.purple"
"syntax.none" = "pallet.transparent"
"syntax.preproc" = "pallet.blue"
"syntax.define" = "pallet.blue"
"syntax.punctuation.special" = "pallet.foreground"
"syntax.string.regex" = "pallet.green"
"syntax.string.regexp" = "pallet.green"
"syntax.string.escape" = "pallet.green"
"syntax.string.special" = "pallet.green"
"syntax.string.special.path" = "pallet.green"
"syntax.string.special.symbol" = "pallet.foreground"
"syntax.string.special.url" = "pallet.green"
"syntax.character" = "pallet.green"
"syntax.character.special" = "pallet.green"
"syntax.boolean" = "pallet.purple"
"syntax.number" = "pallet.purple"
"syntax.number.float" = "pallet.purple"
"syntax.float" = "pallet.purple"
"syntax.function.builtin" = "pallet.yellow"
"syntax.function.call" = "pallet.yellow"
"syntax.function.method" = "pallet.blue"
"syntax.method" = "pallet.yellow"
"syntax.method.call" = "pallet.yellow"
"syntax.parameter" = "pallet.purple"
"syntax.keyword.conditional" = "pallet.red"
"syntax.keyword.debug" = "pallet.red"
"syntax.keyword.directive" = "pallet.blue"
"syntax.keyword.directive.define" = "pallet.blue"
"syntax.keyword.exception" = "pallet.red"
"syntax.keyword.function" = "pallet.red"
"syntax.keyword.import" = "pallet.red"
"syntax.keyword.operator" = "pallet.orange"
"syntax.keyword.repeat" = "pallet.red"
"syntax.keyword.return" = "pallet.red"
"syntax.keyword.storage" = "pallet.aqua"
"syntax.conditional" = "pallet.red"
"syntax.repeat" = "pallet.red"
"syntax.debug" = "pallet.red"
"syntax.include" = "pallet.red"
"syntax.exception" = "pallet.red"
"syntax.type.definition" = "pallet.aqua"
"syntax.type.qualifier" = "pallet.aqua"
"syntax.storageclass" = "pallet.aqua"
"syntax.field" = "pallet.aqua"
"syntax.variable.member" = "pallet.aqua"
"syntax.variable.parameter" = "pallet.purple"
"syntax.constant.macro" = "pallet.orange"
"syntax.markup" = "pallet.foreground"
"syntax.markup.strong" = "pallet.aqua"
"syntax.markup.italic" = "pallet.red"
"syntax.markup.underline" = "pallet.green"
"syntax.markup.strikethrough" = "pallet.foreground-subtle"
"syntax.markup.heading" = "pallet.foreground"
"syntax.markup.raw" = "pallet.green"
"syntax.markup.math" = "pallet.orange"
"syntax.markup.environment" = "pallet.orange"
"syntax.markup.environment.name" = "pallet.aqua"
"syntax.markup.link" = "pallet.green"
"syntax.markup.link.label" = "pallet.foreground"
"syntax.markup.list" = "pallet.foreground"
"syntax.markup.list.checked" = "pallet.green"
"syntax.markup.list.unchecked" = "pallet.foreground-subtle"
"syntax.comment.todo" = "pallet.yellow"
"syntax.comment.note" = "pallet.red"
"syntax.comment.warning" = "pallet.orange"
"syntax.comment.error" = "pallet.red"
"syntax.diff.plus" = "pallet.green"
"syntax.diff.minus" = "pallet.red"
"syntax.diff.delta" = "pallet.orange"
"syntax.namespace" = "pallet.green"
"syntax.symbol" = "pallet.foreground"
"syntax.text" = "pallet.foreground"
"syntax.text.strong" = "pallet.aqua"
"syntax.text.emphasis" = "pallet.red"
"syntax.text.underline" = "pallet.green"
"syntax.text.strike" = "pallet.foreground-subtle"
"syntax.text.title" = "pallet.yellow"
"syntax.text.literal" = "pallet.green"
"syntax.text.uri" = "pallet.green"
"syntax.text.math" = "pallet.orange"
"syntax.text.environment" = "pallet.orange"
"syntax.text.environment.name" = "pallet.aqua"
"syntax.text.reference" = "pallet.blue"
"syntax.text.todo" = "pallet.yellow"
"syntax.text.todo.checked" = "pallet.green"
"syntax.text.todo.unchecked" = "pallet.foreground-subtle"
"syntax.text.note" = "pallet.red"
"syntax.text.note.comment" = "pallet.red"
"syntax.text.warning" = "pallet.orange"
"syntax.text.danger" = "pallet.red"
"syntax.text.danger.comment" = "pallet.red"
"syntax.text.diff.add" = "pallet.green"
"syntax.text.diff.delete" = "pallet.red"
"syntax.tag" = "pallet.red"
"syntax.tag.attribute" = "pallet.blue"
"syntax.tag.delimiter" = "pallet.foreground"
"syntax.punctuation" = "pallet.foreground"
"syntax.macro" = "pallet.orange"
"syntax.structure" = "pallet.aqua"
"syntax.lsp.type.class" = "pallet.aqua"
"syntax.lsp.type.comment" = "pallet.foreground-subtle"
"syntax.lsp.type.decorator" = "pallet.orange"
"syntax.lsp.type.enum" = "pallet.aqua"
"syntax.lsp.type.enumMember" = "pallet.purple"
"syntax.lsp.type.function" = "pallet.yellow"
"syntax.lsp.type.interface" = "pallet.aqua"
"syntax.lsp.type.macro" = "pallet.orange"
"syntax.lsp.type.method" = "pallet.yellow"
"syntax.lsp.type.modifier.java" = "pallet.red"
"syntax.lsp.type.namespace" = "pallet.green"
"syntax.lsp.type.parameter" = "pallet.foreground"
"syntax.lsp.type.property" = "pallet.aqua"
"syntax.lsp.type.struct" = "pallet.aqua"
"syntax.lsp.type.type" = "pallet.aqua"
"syntax.lsp.type.typeParameter" = "pallet.aqua"
"syntax.lsp.type.variable" = "pallet.foreground"

[options]
"ui.line-number.relative" = true
scrolloff = 5
font = "Liga Berkeley Mono"
font_size = 18
cursor_roundness = 2
picker_roundness = 16

[langs.rust]
indent = 4
format_on_save = false
use_tabs = false

[langs.c]
indent = 4
format_on_save = true
use_tabs = false

[langs.cpp]
indent = 4
format_on_save = true
use_tabs = false

[langs.csharp]
indent = 4
format_on_save = true
use_tabs = false

[langs.css]
indent = 2
format_on_save = false
use_tabs = false

[langs.gitcommit]
indent = 4
format_on_save = false
use_tabs = false

[langs.go]
indent = 4
format_on_save = true
use_tabs = false

[langs.html]
indent = 2
format_on_save = false
use_tabs = false

[langs.javascript]
indent = 2
format_on_save = false
use_tabs = false

[langs.jsx]
indent = 2
format_on_save = false
use_tabs = false

[langs.json]
indent = 2
format_on_save = false
use_tabs = false

[langs.make]
indent = 4
format_on_save = false
use_tabs = true

[langs.markdown]
indent = 0
format_on_save = false
use_tabs = false

[langs.odin]
indent = 4
format_on_save = true
use_tabs = false

[langs.python]
indent = 4
format_on_save = true
use_tabs = false

[langs.scss]
indent = 2
format_on_save = false
use_tabs = false

[langs.sql]
indent = 2
format_on_save = false
use_tabs = false

[langs.typescript]
indent = 2
format_on_save = false
use_tabs = false

[langs.tsx]
indent = 2
format_on_save = false
use_tabs = false

[langs.toml]
indent = 4
format_on_save = false
use_tabs = false

[langs.yaml]
indent = 2
format_on_save = false
use_tabs = false

[langs.zig]
indent = 4
format_on_save = true
use_tabs = false
