id = "gruvbox-light"
name = "Gruvbox Light"

[tokens]
"ui.background" = "#fbf1c7"
"ui.foreground" = "#3c3836"
"ui.input.background" = "#fbf1c7"
"ui.input.foreground" = "#3c3836"
"ui.yank-flash" = "#4585886e"
"ui.statusline.active" = "#076678"
"ui.statusline.inactive" = "#928374"
# Git status
"git.status.section.header" = "#b57614"
"git.status.section.count" = "#928374"
"git.status.header.label" = "#076678"
"git.status.header.value" = "#79740e"
"git.status.header.hash" = "#928374"
"git.status.header.summary" = "#3c3836"
"git.status.in-progress" = "#427b58"
"git.status.entry.added" = "#79740e"
"git.status.entry.modified" = "#b57614"
"git.status.entry.deleted" = "#af3a03"
"git.status.entry.renamed" = "#8f3f71"
"git.status.entry.copied" = "#427b58"
"git.status.entry.updated" = "#076678"
"git.status.entry.changed" = "#79740e"
"git.status.entry.untracked" = "#af3a03"
"git.status.entry.path" = "#3c3836"
"git.status.commit.hash" = "#928374"
"git.status.commit.summary" = "#3c3836"
"git.status.stash.name" = "#b57614"
"git.status.stash.summary" = "#3c3836"
"git.status.command" = "#076678"
"git.status.message" = "#928374"
"syntax.attribute" = "#076678"
"syntax.comment" = "#928374"
"syntax.constant" = "#b57614"
"syntax.constant.builtin" = "#b57614"
"syntax.constructor" = "#8f3f71"
"syntax.function" = "#076678"
"syntax.function.macro" = "#af3a03"
"syntax.keyword" = "#af3a03"
"syntax.label" = "#af3a03"
"syntax.module" = "#79740e"
"syntax.operator" = "#af3a03"
"syntax.property" = "#b57614"
"syntax.punctuation.bracket" = "#3c3836"
"syntax.punctuation.delimiter" = "#3c3836"
"syntax.string" = "#79740e"
"syntax.type" = "#427b58"
"syntax.type.builtin" = "#427b58"
"syntax.variable" = "#3c3836"
"syntax.variable.builtin" = "#8f3f71"

[options]
"ui.line-number.relative" = true
"ui.nerd-fonts" = true
font = "default"
font_size = 18
cursor_roundness = 2
picker_roundness = 16

[langs.rust]
indent = 4
format_on_save = true
use_tabs = false

[langs.markdown]
indent = 0
format_on_save = false
use_tabs = false
