id = "gruvbox-light"
name = "Gruvbox Light"
opacity = 1.0
blend_mode = "opacity"

[tokens]
"ui.background" = "#fbf1c7"
"ui.foreground" = "#3c3836"
"syntax.attribute" = "#076678"
"syntax.comment" = "#928374"
"syntax.constant" = "#8f3f71"
"syntax.constant.builtin" = "#8f3f71"
"syntax.constructor" = "#427b58"
"syntax.function" = "#79740e"
"syntax.function.macro" = "#b57614"
"syntax.keyword" = "#9d0006"
"syntax.label" = "#9d0006"
"syntax.module" = "#b57614"
"syntax.operator" = "#af3a03"
"syntax.property" = "#076678"
"syntax.punctuation.bracket" = "#3c3836"
"syntax.punctuation.delimiter" = "#3c3836"
"syntax.string" = "#79740e"
"syntax.type" = "#b57614"
"syntax.type.builtin" = "#b57614"
"syntax.variable" = "#076678"
"syntax.variable.builtin" = "#076678"
