id = "gruvbox-dark"
name = "Gruvbox Dark"

[tokens]
"ui.background" = "#282828"
"ui.foreground" = "#ebdbb2"
"ui.yank-flash" = "#83a5986e"
"syntax.attribute" = "#83a598"
"syntax.comment" = "#928374"
"syntax.constant" = "#d3869b"
"syntax.constant.builtin" = "#d3869b"
"syntax.constructor" = "#8ec07c"
"syntax.function" = "#fabd2f"
"syntax.function.macro" = "#fe8019"
"syntax.keyword" = "#fb4934"
"syntax.label" = "#fb4934"
"syntax.module" = "#b8bb26"
"syntax.operator" = "#fe8019"
"syntax.property" = "#8ec07c"
"syntax.punctuation.bracket" = "#ebdbb2"
"syntax.punctuation.delimiter" = "#ebdbb2"
"syntax.string" = "#b8bb26"
"syntax.type" = "#8ec07c"
"syntax.type.builtin" = "#8ec07c"
"syntax.variable" = "#ebdbb2"
"syntax.variable.builtin" = "#d3869b"

[options]
"ui.line-number.relative" = true
font = "default"
font_size = 18
cursor_roundness = 2
picker_roundness = 16
