id = "gruvbox-light"
name = "Gruvbox Light"


[pallet]
background = "#fbf1c7"
surface = "#e9dfb5"
surface-muted = "#e5dbb1"
surface-header = "#e3d9af"
surface-selection = "#e1d7ad"
surface-hover-selection = "#dbd1a7"
border = "#ddd3a9"
border-strong = "#cbc197"
selection = "#374763"
foreground = "#3c3836"
foreground-muted = "#8c8570"
foreground-subtle = "#928374"
cursor = "#6eaaff"
blue = "#076678"
blue-overlay = "#4585886e"
green = "#79740e"
yellow = "#b57614"
red = "#af3a03"
red-strong = "#cc241d"
aqua = "#427b58"
purple = "#8f3f71"

[tokens]
"ui.background" = "pallet.background"
"ui.foreground" = "pallet.foreground"
"ui.cursor" = "pallet.cursor"
"ui.selection" = "pallet.selection"
"ui.picker.highlight" = "pallet.blue"
"ui.input.background" = "pallet.background"
"ui.input.foreground" = "pallet.foreground"
"ui.autocomplete.background" = "pallet.surface"
"ui.autocomplete.foreground" = "pallet.foreground"
"ui.autocomplete.muted" = "pallet.foreground-muted"
"ui.autocomplete.border" = "pallet.border"
"ui.autocomplete.selection" = "pallet.surface-selection"
"ui.autocomplete.documentation.background" = "pallet.surface-muted"
"ui.hover.background" = "pallet.surface"
"ui.hover.foreground" = "pallet.foreground"
"ui.hover.muted" = "pallet.foreground-muted"
"ui.hover.border" = "pallet.border"
"ui.hover.focused.border" = "pallet.border-strong"
"ui.hover.header.background" = "pallet.surface-header"
"ui.hover.selection" = "pallet.surface-hover-selection"
"ui.yank-flash" = "pallet.blue-overlay"
"ui.statusline.active" = "pallet.blue"
"ui.statusline.inactive" = "pallet.foreground-subtle"
"ui.notification.background" = "pallet.surface"
"ui.notification.foreground" = "pallet.foreground"
"ui.notification.title" = "pallet.foreground"
"ui.notification.muted" = "pallet.foreground-muted"
"ui.notification.border" = "pallet.border"
"ui.notification.progress.background" = "pallet.surface-hover-selection"
"ui.notification.progress.fill" = "pallet.blue"
"ui.notification.info" = "pallet.blue"
"ui.notification.success" = "pallet.green"
"ui.notification.warning" = "pallet.yellow"
"ui.notification.error" = "pallet.red-strong"
# Git status
"git.status.section.header" = "pallet.yellow"
"git.status.section.count" = "pallet.foreground-subtle"
"git.status.header.label" = "pallet.blue"
"git.status.header.value" = "pallet.green"
"git.status.header.hash" = "pallet.foreground-subtle"
"git.status.header.summary" = "pallet.foreground"
"git.status.in-progress" = "pallet.aqua"
"git.status.entry.added" = "pallet.green"
"git.status.entry.modified" = "pallet.yellow"
"git.status.entry.deleted" = "pallet.red"
"git.status.entry.renamed" = "pallet.purple"
"git.status.entry.copied" = "pallet.aqua"
"git.status.entry.updated" = "pallet.blue"
"git.status.entry.changed" = "pallet.green"
"git.status.entry.untracked" = "pallet.red"
"git.status.entry.path" = "pallet.foreground"
"git.status.commit.hash" = "pallet.foreground-subtle"
"git.status.commit.summary" = "pallet.foreground"
"git.status.stash.name" = "pallet.yellow"
"git.status.stash.summary" = "pallet.foreground"
"git.status.command" = "pallet.blue"
"git.status.message" = "pallet.foreground-subtle"
# Git fringe
"git.fringe.added" = "pallet.green"
"git.fringe.modified" = "pallet.yellow"
"git.fringe.removed" = "pallet.red"
"syntax.attribute" = "pallet.blue"
"syntax.attribute.builtin" = "pallet.blue"
"syntax.comment" = "pallet.foreground-subtle"
"syntax.comment.documentation" = "pallet.foreground-subtle"
"syntax.constant" = "pallet.yellow"
"syntax.constant.builtin" = "pallet.yellow"
"syntax.constructor" = "pallet.purple"
"syntax.function" = "pallet.blue"
"syntax.function.macro" = "pallet.red"
"syntax.keyword" = "pallet.red"
"syntax.keyword.coroutine" = "pallet.red"
"syntax.keyword.modifier" = "pallet.red"
"syntax.label" = "pallet.red"
"syntax.module" = "pallet.green"
"syntax.module.builtin" = "pallet.green"
"syntax.operator" = "pallet.red"
"syntax.property" = "pallet.yellow"
"syntax.punctuation.bracket" = "pallet.foreground"
"syntax.punctuation.delimiter" = "pallet.foreground"
"syntax.string" = "pallet.green"
"syntax.string.documentation" = "pallet.green"
"syntax.type" = "pallet.aqua"
"syntax.type.builtin" = "pallet.aqua"
"syntax.variable" = "pallet.foreground"
"syntax.variable.builtin" = "pallet.purple"
"syntax.none" = "pallet.foreground"
"syntax.preproc" = "pallet.blue"
"syntax.define" = "pallet.blue"
"syntax.punctuation.special" = "pallet.foreground"
"syntax.string.regex" = "pallet.green"
"syntax.string.regexp" = "pallet.green"
"syntax.string.escape" = "pallet.green"
"syntax.string.special" = "pallet.green"
"syntax.string.special.path" = "pallet.green"
"syntax.string.special.symbol" = "pallet.foreground"
"syntax.string.special.url" = "pallet.green"
"syntax.character" = "pallet.green"
"syntax.character.special" = "pallet.green"
"syntax.boolean" = "pallet.yellow"
"syntax.number" = "pallet.yellow"
"syntax.number.float" = "pallet.yellow"
"syntax.float" = "pallet.yellow"
"syntax.function.builtin" = "pallet.blue"
"syntax.function.call" = "pallet.blue"
"syntax.function.method" = "pallet.blue"
"syntax.function.method.call" = "pallet.blue"
"syntax.method" = "pallet.blue"
"syntax.method.call" = "pallet.blue"
"syntax.parameter" = "pallet.foreground"
"syntax.keyword.conditional" = "pallet.red"
"syntax.keyword.conditional.ternary" = "pallet.red"
"syntax.keyword.debug" = "pallet.red"
"syntax.keyword.directive" = "pallet.blue"
"syntax.keyword.directive.define" = "pallet.blue"
"syntax.keyword.exception" = "pallet.red"
"syntax.keyword.function" = "pallet.red"
"syntax.keyword.import" = "pallet.red"
"syntax.keyword.operator" = "pallet.red"
"syntax.keyword.repeat" = "pallet.red"
"syntax.keyword.return" = "pallet.red"
"syntax.keyword.storage" = "pallet.aqua"
"syntax.keyword.type" = "pallet.aqua"
"syntax.conditional" = "pallet.red"
"syntax.repeat" = "pallet.red"
"syntax.debug" = "pallet.red"
"syntax.include" = "pallet.red"
"syntax.exception" = "pallet.red"
"syntax.type.definition" = "pallet.aqua"
"syntax.type.qualifier" = "pallet.aqua"
"syntax.storageclass" = "pallet.aqua"
"syntax.field" = "pallet.yellow"
"syntax.variable.member" = "pallet.yellow"
"syntax.variable.parameter" = "pallet.foreground"
"syntax.variable.parameter.builtin" = "pallet.foreground"
"syntax.constant.macro" = "pallet.red"
"syntax.markup" = "pallet.foreground"
"syntax.markup.strong" = "pallet.aqua"
"syntax.markup.italic" = "pallet.red"
"syntax.markup.underline" = "pallet.green"
"syntax.markup.strikethrough" = "pallet.foreground-subtle"
"syntax.markup.heading" = "pallet.red"
"syntax.markup.heading.1" = "pallet.red"
"syntax.markup.heading.2" = "pallet.red"
"syntax.markup.heading.3" = "pallet.red"
"syntax.markup.heading.4" = "pallet.red"
"syntax.markup.heading.5" = "pallet.red"
"syntax.markup.heading.6" = "pallet.red"
"syntax.markup.raw" = "pallet.green"
"syntax.markup.raw.block" = "pallet.green"
"syntax.markup.math" = "pallet.red"
"syntax.markup.environment" = "pallet.red"
"syntax.markup.environment.name" = "pallet.aqua"
"syntax.markup.link" = "pallet.green"
"syntax.markup.link.url" = "pallet.green"
"syntax.markup.link.label" = "pallet.foreground"
"syntax.markup.list" = "pallet.foreground"
"syntax.markup.list.checked" = "pallet.green"
"syntax.markup.list.unchecked" = "pallet.foreground-subtle"
"syntax.markup.quote" = "pallet.foreground-subtle"
"syntax.comment.todo" = "pallet.green"
"syntax.comment.note" = "pallet.red"
"syntax.comment.warning" = "pallet.yellow"
"syntax.comment.error" = "pallet.red"
"syntax.diff.plus" = "pallet.green"
"syntax.diff.minus" = "pallet.red"
"syntax.diff.delta" = "pallet.yellow"
"syntax.namespace" = "pallet.green"
"syntax.symbol" = "pallet.foreground"
"syntax.text" = "pallet.foreground"
"syntax.text.strong" = "pallet.aqua"
"syntax.text.emphasis" = "pallet.red"
"syntax.text.underline" = "pallet.green"
"syntax.text.strike" = "pallet.foreground-subtle"
"syntax.text.title" = "pallet.red"
"syntax.text.literal" = "pallet.green"
"syntax.text.uri" = "pallet.green"
"syntax.text.math" = "pallet.red"
"syntax.text.environment" = "pallet.red"
"syntax.text.environment.name" = "pallet.aqua"
"syntax.text.reference" = "pallet.foreground"
"syntax.text.todo" = "pallet.green"
"syntax.text.todo.checked" = "pallet.green"
"syntax.text.todo.unchecked" = "pallet.foreground-subtle"
"syntax.text.note" = "pallet.red"
"syntax.text.note.comment" = "pallet.red"
"syntax.text.warning" = "pallet.yellow"
"syntax.text.danger" = "pallet.red"
"syntax.text.danger.comment" = "pallet.red"
"syntax.text.diff.add" = "pallet.green"
"syntax.text.diff.delete" = "pallet.red"
"syntax.tag" = "pallet.red"
"syntax.tag.builtin" = "pallet.red"
"syntax.tag.attribute" = "pallet.blue"
"syntax.tag.delimiter" = "pallet.foreground"
"syntax.punctuation" = "pallet.foreground"
"syntax.macro" = "pallet.red"
"syntax.structure" = "pallet.aqua"
"syntax.lsp.type.class" = "pallet.aqua"
"syntax.lsp.type.comment" = "pallet.foreground-subtle"
"syntax.lsp.type.decorator" = "pallet.red"
"syntax.lsp.type.enum" = "pallet.aqua"
"syntax.lsp.type.enumMember" = "pallet.yellow"
"syntax.lsp.type.function" = "pallet.blue"
"syntax.lsp.type.interface" = "pallet.purple"
"syntax.lsp.type.macro" = "pallet.red"
"syntax.lsp.type.method" = "pallet.blue"
"syntax.lsp.type.modifier.java" = "pallet.red"
"syntax.lsp.type.namespace" = "pallet.green"
"syntax.lsp.type.parameter" = "pallet.foreground"
"syntax.lsp.type.property" = "pallet.yellow"
"syntax.lsp.type.struct" = "pallet.aqua"
"syntax.lsp.type.type" = "pallet.aqua"
"syntax.lsp.type.typeParameter" = "pallet.aqua"
"syntax.lsp.type.variable" = "pallet.foreground"
