id = "volt-light"
name = "Volt Light"

[tokens]
"ui.background" = "#f5f6f7"
"ui.foreground" = "#383a42"
"ui.input.background" = "#f5f6f7"
"ui.input.foreground" = "#383a42"
"ui.yank-flash" = "#61afef6e"
# Git status
"git.status.section.header" = "#986801"
"git.status.section.count" = "#a0a1a7"
"git.status.header.label" = "#4078f2"
"git.status.header.value" = "#c18401"
"git.status.header.hash" = "#a0a1a7"
"git.status.header.summary" = "#383a42"
"git.status.in-progress" = "#0184bc"
"git.status.entry.added" = "#50a14f"
"git.status.entry.modified" = "#986801"
"git.status.entry.deleted" = "#e45649"
"git.status.entry.renamed" = "#a626a4"
"git.status.entry.copied" = "#0184bc"
"git.status.entry.updated" = "#4078f2"
"git.status.entry.changed" = "#c18401"
"git.status.entry.untracked" = "#e45649"
"git.status.entry.path" = "#383a42"
"git.status.commit.hash" = "#a0a1a7"
"git.status.commit.summary" = "#383a42"
"git.status.stash.name" = "#986801"
"git.status.stash.summary" = "#383a42"
"git.status.command" = "#4078f2"
"git.status.message" = "#a0a1a7"
"syntax.attribute" = "#4078f2"
"syntax.comment" = "#a0a1a7"
"syntax.constant" = "#986801"
"syntax.constant.builtin" = "#986801"
"syntax.constructor" = "#a626a4"
"syntax.function" = "#4078f2"
"syntax.function.macro" = "#0184bc"
"syntax.keyword" = "#a626a4"
"syntax.label" = "#e45649"
"syntax.module" = "#c18401"
"syntax.operator" = "#0184bc"
"syntax.property" = "#e45649"
"syntax.punctuation.bracket" = "#383a42"
"syntax.punctuation.delimiter" = "#383a42"
"syntax.string" = "#50a14f"
"syntax.type" = "#c18401"
"syntax.type.builtin" = "#c18401"
"syntax.variable" = "#e45649"
"syntax.variable.builtin" = "#e45649"

[options]
"ui.line-number.relative" = true
font = "default"
font_size = 18
cursor_roundness = 2
picker_roundness = 16

[langs.rust]
indent = 4
format_on_save = true
use_tabs = false

[langs.markdown]
indent = 0
format_on_save = false
use_tabs = false
