id = "vscode-light"
name = "VS Code Light"

[tokens]
"ui.background" = "#ffffff"
"ui.foreground" = "#000000"
"syntax.attribute" = "#0070c1"
"syntax.comment" = "#008000"
"syntax.constant" = "#0070c1"
"syntax.constant.builtin" = "#0000ff"
"syntax.constructor" = "#267f99"
"syntax.function" = "#795e26"
"syntax.function.macro" = "#795e26"
"syntax.keyword" = "#0000ff"
"syntax.label" = "#000000"
"syntax.module" = "#267f99"
"syntax.operator" = "#000000"
"syntax.property" = "#0070c1"
"syntax.punctuation.bracket" = "#000000"
"syntax.punctuation.delimiter" = "#000000"
"syntax.string" = "#a31515"
"syntax.type" = "#267f99"
"syntax.type.builtin" = "#0000ff"
"syntax.variable" = "#0070c1"
"syntax.variable.builtin" = "#0000ff"
