id = "vscode-light"
name = "VS Code Light"

[tokens]
"ui.background" = "#ffffff"
"ui.foreground" = "#333333"
"ui.cursor" = "#6eaaff"
"ui.selection" = "#374763"
"ui.input.background" = "#ffffff"
"ui.input.foreground" = "#333333"
"ui.autocomplete.background" = "#ededed"
"ui.autocomplete.foreground" = "#333333"
"ui.autocomplete.muted" = "#898989"
"ui.autocomplete.border" = "#e1e1e1"
"ui.autocomplete.selection" = "#e5e5e5"
"ui.autocomplete.documentation.background" = "#e9e9e9"
"ui.hover.background" = "#ededed"
"ui.hover.foreground" = "#333333"
"ui.hover.muted" = "#898989"
"ui.hover.border" = "#e1e1e1"
"ui.hover.focused.border" = "#cfcfcf"
"ui.hover.header.background" = "#e7e7e7"
"ui.hover.selection" = "#dfdfdf"
"ui.yank-flash" = "#007acc6e"
"ui.statusline.active" = "#0070c1"
"ui.statusline.inactive" = "#008000"
# Git status
"git.status.section.header" = "#795e26"
"git.status.section.count" = "#008000"
"git.status.header.label" = "#0070c1"
"git.status.header.value" = "#267f99"
"git.status.header.hash" = "#008000"
"git.status.header.summary" = "#333333"
"git.status.in-progress" = "#267f99"
"git.status.entry.added" = "#008000"
"git.status.entry.modified" = "#795e26"
"git.status.entry.deleted" = "#a31515"
"git.status.entry.renamed" = "#af00db"
"git.status.entry.copied" = "#0070c1"
"git.status.entry.updated" = "#267f99"
"git.status.entry.changed" = "#795e26"
"git.status.entry.untracked" = "#a31515"
"git.status.entry.path" = "#333333"
"git.status.commit.hash" = "#008000"
"git.status.commit.summary" = "#333333"
"git.status.stash.name" = "#795e26"
"git.status.stash.summary" = "#333333"
"git.status.command" = "#0070c1"
"git.status.message" = "#008000"
# Git fringe
"git.fringe.added" = "#008000"
"git.fringe.modified" = "#795e26"
"git.fringe.removed" = "#a31515"
"syntax.attribute" = "#001080"
"syntax.comment" = "#008000"
"syntax.constant" = "#0070c1"
"syntax.constant.builtin" = "#0070c1"
"syntax.constructor" = "#267f99"
"syntax.function" = "#795e26"
"syntax.function.macro" = "#af00db"
"syntax.keyword" = "#0000ff"
"syntax.label" = "#0000ff"
"syntax.module" = "#267f99"
"syntax.operator" = "#333333"
"syntax.property" = "#001080"
"syntax.punctuation.bracket" = "#333333"
"syntax.punctuation.delimiter" = "#333333"
"syntax.string" = "#a31515"
"syntax.type" = "#267f99"
"syntax.type.builtin" = "#267f99"
"syntax.variable" = "#001080"
"syntax.variable.builtin" = "#795e26"
"syntax.none" = "#00000000"
"syntax.preproc" = "#001080"
"syntax.define" = "#001080"
"syntax.punctuation.special" = "#333333"
"syntax.string.regex" = "#a31515"
"syntax.string.regexp" = "#a31515"
"syntax.string.escape" = "#a31515"
"syntax.string.special" = "#a31515"
"syntax.string.special.path" = "#a31515"
"syntax.string.special.symbol" = "#001080"
"syntax.string.special.url" = "#a31515"
"syntax.character" = "#a31515"
"syntax.character.special" = "#a31515"
"syntax.boolean" = "#0070c1"
"syntax.number" = "#0070c1"
"syntax.number.float" = "#0070c1"
"syntax.float" = "#0070c1"
"syntax.function.builtin" = "#795e26"
"syntax.function.call" = "#795e26"
"syntax.function.method" = "#795e26"
"syntax.method" = "#795e26"
"syntax.method.call" = "#795e26"
"syntax.parameter" = "#001080"
"syntax.keyword.conditional" = "#0000ff"
"syntax.keyword.debug" = "#0000ff"
"syntax.keyword.directive" = "#001080"
"syntax.keyword.directive.define" = "#001080"
"syntax.keyword.exception" = "#0000ff"
"syntax.keyword.function" = "#0000ff"
"syntax.keyword.import" = "#0000ff"
"syntax.keyword.operator" = "#333333"
"syntax.keyword.repeat" = "#0000ff"
"syntax.keyword.return" = "#0000ff"
"syntax.keyword.storage" = "#267f99"
"syntax.conditional" = "#0000ff"
"syntax.repeat" = "#0000ff"
"syntax.debug" = "#0000ff"
"syntax.include" = "#0000ff"
"syntax.exception" = "#0000ff"
"syntax.type.definition" = "#267f99"
"syntax.type.qualifier" = "#267f99"
"syntax.storageclass" = "#267f99"
"syntax.field" = "#001080"
"syntax.variable.member" = "#001080"
"syntax.variable.parameter" = "#001080"
"syntax.constant.macro" = "#af00db"
"syntax.markup" = "#333333"
"syntax.markup.strong" = "#267f99"
"syntax.markup.italic" = "#0000ff"
"syntax.markup.underline" = "#a31515"
"syntax.markup.strikethrough" = "#008000"
"syntax.markup.heading" = "#0000ff"
"syntax.markup.raw" = "#a31515"
"syntax.markup.math" = "#af00db"
"syntax.markup.environment" = "#af00db"
"syntax.markup.environment.name" = "#267f99"
"syntax.markup.link" = "#a31515"
"syntax.markup.link.label" = "#001080"
"syntax.markup.list" = "#333333"
"syntax.markup.list.checked" = "#008000"
"syntax.markup.list.unchecked" = "#008000"
"syntax.comment.todo" = "#795e26"
"syntax.comment.note" = "#0000ff"
"syntax.comment.warning" = "#795e26"
"syntax.comment.error" = "#0000ff"
"syntax.diff.plus" = "#008000"
"syntax.diff.minus" = "#a31515"
"syntax.diff.delta" = "#795e26"
"syntax.namespace" = "#267f99"
"syntax.symbol" = "#001080"
"syntax.text" = "#333333"
"syntax.text.strong" = "#267f99"
"syntax.text.emphasis" = "#0000ff"
"syntax.text.underline" = "#a31515"
"syntax.text.strike" = "#008000"
"syntax.text.title" = "#0000ff"
"syntax.text.literal" = "#a31515"
"syntax.text.uri" = "#a31515"
"syntax.text.math" = "#af00db"
"syntax.text.environment" = "#af00db"
"syntax.text.environment.name" = "#267f99"
"syntax.text.reference" = "#001080"
"syntax.text.todo" = "#795e26"
"syntax.text.todo.checked" = "#008000"
"syntax.text.todo.unchecked" = "#008000"
"syntax.text.note" = "#0000ff"
"syntax.text.note.comment" = "#0000ff"
"syntax.text.warning" = "#795e26"
"syntax.text.danger" = "#0000ff"
"syntax.text.danger.comment" = "#0000ff"
"syntax.text.diff.add" = "#008000"
"syntax.text.diff.delete" = "#a31515"
"syntax.tag" = "#0000ff"
"syntax.tag.attribute" = "#001080"
"syntax.tag.delimiter" = "#333333"
"syntax.punctuation" = "#333333"
"syntax.macro" = "#af00db"
"syntax.structure" = "#267f99"
"syntax.lsp.type.class" = "#267f99"
"syntax.lsp.type.comment" = "#008000"
"syntax.lsp.type.decorator" = "#af00db"
"syntax.lsp.type.enum" = "#267f99"
"syntax.lsp.type.enumMember" = "#0070c1"
"syntax.lsp.type.function" = "#795e26"
"syntax.lsp.type.interface" = "#267f99"
"syntax.lsp.type.macro" = "#af00db"
"syntax.lsp.type.method" = "#795e26"
"syntax.lsp.type.modifier.java" = "#0000ff"
"syntax.lsp.type.namespace" = "#267f99"
"syntax.lsp.type.parameter" = "#001080"
"syntax.lsp.type.property" = "#001080"
"syntax.lsp.type.struct" = "#267f99"
"syntax.lsp.type.type" = "#267f99"
"syntax.lsp.type.typeParameter" = "#267f99"
"syntax.lsp.type.variable" = "#001080"

[options]
"ui.line-number.relative" = true
font = "default"
font_size = 18
cursor_roundness = 2
picker_roundness = 16

[langs.rust]
indent = 4
format_on_save = true
use_tabs = false

[langs.markdown]
indent = 0
format_on_save = false
use_tabs = false
