id = "vscode-dark"
name = "VS Code Dark"

[tokens]
"ui.background" = "#1e1e1e"
"ui.foreground" = "#d4d4d4"
"ui.input.background" = "#1e1e1e"
"ui.input.foreground" = "#d4d4d4"
"ui.yank-flash" = "#569cd66e"
# Git status
"git.status.section.header" = "#ce9178"
"git.status.section.count" = "#6a9955"
"git.status.header.label" = "#4fc1ff"
"git.status.header.value" = "#dcdcaa"
"git.status.header.hash" = "#6a9955"
"git.status.header.summary" = "#d4d4d4"
"git.status.in-progress" = "#4ec9b0"
"git.status.entry.added" = "#4ec9b0"
"git.status.entry.modified" = "#ce9178"
"git.status.entry.deleted" = "#f44747"
"git.status.entry.renamed" = "#c586c0"
"git.status.entry.copied" = "#4fc1ff"
"git.status.entry.updated" = "#9cdcfe"
"git.status.entry.changed" = "#dcdcaa"
"git.status.entry.untracked" = "#f44747"
"git.status.entry.path" = "#d4d4d4"
"git.status.commit.hash" = "#6a9955"
"git.status.commit.summary" = "#d4d4d4"
"git.status.stash.name" = "#ce9178"
"git.status.stash.summary" = "#d4d4d4"
"git.status.command" = "#4fc1ff"
"git.status.message" = "#6a9955"
"syntax.attribute" = "#9cdcfe"
"syntax.comment" = "#6a9955"
"syntax.constant" = "#4fc1ff"
"syntax.constant.builtin" = "#4fc1ff"
"syntax.constructor" = "#4ec9b0"
"syntax.function" = "#dcdcaa"
"syntax.function.macro" = "#c586c0"
"syntax.keyword" = "#c586c0"
"syntax.label" = "#c586c0"
"syntax.module" = "#4ec9b0"
"syntax.operator" = "#d4d4d4"
"syntax.property" = "#9cdcfe"
"syntax.punctuation.bracket" = "#d4d4d4"
"syntax.punctuation.delimiter" = "#d4d4d4"
"syntax.string" = "#ce9178"
"syntax.type" = "#4ec9b0"
"syntax.type.builtin" = "#4ec9b0"
"syntax.variable" = "#9cdcfe"
"syntax.variable.builtin" = "#4fc1ff"

[options]
"ui.line-number.relative" = true
font = "default"
font_size = 18
cursor_roundness = 2
picker_roundness = 16

[langs.rust]
indent = 4
format_on_save = true
use_tabs = false

[langs.markdown]
indent = 0
format_on_save = false
use_tabs = false
