id = "vscode-dark"
name = "VS Code Dark"

[pallet]
background = "#1e1e1e"
surface = "#303030"
surface-muted = "#343434"
surface-header = "#363636"
surface-selection = "#383838"
surface-hover-selection = "#3e3e3e"
commandline-overlay = "#00000000"
border = "#3c3c3c"
border-strong = "#4e4e4e"
selection = "#374763"
foreground = "#d4d4d4"
foreground-muted = "#898989"
cursor = "#6eaaff"
blue = "#4fc1ff"
blue-light = "#9cdcfe"
blue-overlay = "#569cd66e"
green = "#6a9955"
yellow = "#dcdcaa"
yellow-dark = "#cca700"
red = "#f44747"
red-soft = "#f14c4c"
orange = "#ce9178"
aqua = "#4ec9b0"
purple = "#c586c0"

[tokens]
"ui.background" = "pallet.background"
"ui.foreground" = "pallet.foreground"
"ui.cursor" = "pallet.cursor"
"ui.selection" = "pallet.selection"
"ui.picker.highlight" = "pallet.blue"
"ui.input.background" = "pallet.background"
"ui.input.foreground" = "pallet.foreground"
"ui.autocomplete.background" = "pallet.surface"
"ui.autocomplete.foreground" = "pallet.foreground"
"ui.autocomplete.muted" = "pallet.foreground-muted"
"ui.autocomplete.border" = "pallet.border"
"ui.autocomplete.selection" = "pallet.surface-selection"
"ui.autocomplete.documentation.background" = "pallet.surface-muted"
"ui.hover.background" = "pallet.surface"
"ui.hover.foreground" = "pallet.foreground"
"ui.hover.muted" = "pallet.foreground-muted"
"ui.hover.border" = "pallet.border"
"ui.hover.focused.border" = "pallet.border-strong"
"ui.hover.header.background" = "pallet.surface-header"
"ui.hover.selection" = "pallet.surface-hover-selection"
"ui.yank-flash" = "pallet.blue-overlay"
"ui.commandline.background" = "pallet.commandline-overlay"
"ui.statusline.active" = "pallet.blue"
"ui.statusline.inactive" = "pallet.green"
"ui.notification.background" = "pallet.surface"
"ui.notification.foreground" = "pallet.foreground"
"ui.notification.title" = "pallet.foreground"
"ui.notification.muted" = "pallet.foreground-muted"
"ui.notification.border" = "pallet.border"
"ui.notification.progress.background" = "pallet.surface-hover-selection"
"ui.notification.progress.fill" = "pallet.blue"
"ui.notification.info" = "pallet.blue"
"ui.notification.success" = "pallet.green"
"ui.notification.warning" = "pallet.yellow-dark"
"ui.notification.error" = "pallet.red-soft"
"ui.panel.background" = "pallet.background"
"ui.panel.header.background" = "pallet.surface"
# Oil directory buffer
"oil.header" = "pallet.orange"
"oil.directory" = "pallet.blue"
"oil.directory.config" = "pallet.yellow"
"oil.directory.git" = "pallet.red-soft"
"oil.directory.github" = "pallet.purple"
"oil.directory.node" = "pallet.aqua"
"oil.file" = "pallet.foreground"
"oil.file.archive" = "pallet.orange"
"oil.file.code" = "pallet.blue"
"oil.file.config" = "pallet.yellow"
"oil.file.document" = "pallet.foreground"
"oil.file.git" = "pallet.red-soft"
"oil.file.image" = "pallet.purple"
"oil.file.lock" = "pallet.red-soft"
"oil.file.media" = "pallet.aqua"
# Git status
"git.status.section.header" = "pallet.orange"
"git.status.section.count" = "pallet.green"
"git.status.header.label" = "pallet.blue"
"git.status.header.value" = "pallet.yellow"
"git.status.header.hash" = "pallet.green"
"git.status.header.summary" = "pallet.foreground"
"git.status.in-progress" = "pallet.aqua"
"git.status.entry.added" = "pallet.aqua"
"git.status.entry.modified" = "pallet.orange"
"git.status.entry.deleted" = "pallet.red"
"git.status.entry.renamed" = "pallet.purple"
"git.status.entry.copied" = "pallet.blue"
"git.status.entry.updated" = "pallet.blue-light"
"git.status.entry.changed" = "pallet.yellow"
"git.status.entry.untracked" = "pallet.red"
"git.status.entry.path" = "pallet.foreground"
"git.status.commit.hash" = "pallet.green"
"git.status.commit.summary" = "pallet.foreground"
"git.status.stash.name" = "pallet.orange"
"git.status.stash.summary" = "pallet.foreground"
"git.status.command" = "pallet.blue"
"git.status.message" = "pallet.green"
# Git fringe
"git.fringe.added" = "pallet.aqua"
"git.fringe.modified" = "pallet.orange"
"git.fringe.removed" = "pallet.red"
"syntax.attribute" = "pallet.blue-light"
"syntax.attribute.builtin" = "pallet.blue-light"
"syntax.comment" = "pallet.green"
"syntax.comment.documentation" = "pallet.green"
"syntax.constant" = "pallet.blue"
"syntax.constant.builtin" = "pallet.blue"
"syntax.constructor" = "pallet.aqua"
"syntax.function" = "pallet.yellow"
"syntax.function.macro" = "pallet.purple"
"syntax.keyword" = "pallet.purple"
"syntax.keyword.coroutine" = "pallet.purple"
"syntax.keyword.modifier" = "pallet.purple"
"syntax.label" = "pallet.purple"
"syntax.module" = "pallet.aqua"
"syntax.module.builtin" = "pallet.aqua"
"syntax.operator" = "pallet.foreground"
"syntax.property" = "pallet.blue-light"
"syntax.punctuation.bracket" = "pallet.foreground"
"syntax.punctuation.delimiter" = "pallet.foreground"
"syntax.string" = "pallet.orange"
"syntax.string.documentation" = "pallet.orange"
"syntax.type" = "pallet.aqua"
"syntax.type.builtin" = "pallet.aqua"
"syntax.variable" = "pallet.blue-light"
"syntax.variable.builtin" = "pallet.blue"
"syntax.none" = "pallet.foreground"
"syntax.preproc" = "pallet.blue-light"
"syntax.define" = "pallet.blue-light"
"syntax.punctuation.special" = "pallet.foreground"
"syntax.string.regex" = "pallet.orange"
"syntax.string.regexp" = "pallet.orange"
"syntax.string.escape" = "pallet.orange"
"syntax.string.special" = "pallet.orange"
"syntax.string.special.path" = "pallet.orange"
"syntax.string.special.symbol" = "pallet.blue-light"
"syntax.string.special.url" = "pallet.orange"
"syntax.character" = "pallet.orange"
"syntax.character.special" = "pallet.orange"
"syntax.boolean" = "pallet.blue"
"syntax.number" = "pallet.blue"
"syntax.number.float" = "pallet.blue"
"syntax.float" = "pallet.blue"
"syntax.function.builtin" = "pallet.yellow"
"syntax.function.call" = "pallet.yellow"
"syntax.function.method" = "pallet.yellow"
"syntax.function.method.call" = "pallet.yellow"
"syntax.method" = "pallet.yellow"
"syntax.method.call" = "pallet.yellow"
"syntax.parameter" = "pallet.blue-light"
"syntax.keyword.conditional" = "pallet.purple"
"syntax.keyword.conditional.ternary" = "pallet.purple"
"syntax.keyword.debug" = "pallet.purple"
"syntax.keyword.directive" = "pallet.blue-light"
"syntax.keyword.directive.define" = "pallet.blue-light"
"syntax.keyword.exception" = "pallet.purple"
"syntax.keyword.function" = "pallet.purple"
"syntax.keyword.import" = "pallet.purple"
"syntax.keyword.operator" = "pallet.foreground"
"syntax.keyword.repeat" = "pallet.purple"
"syntax.keyword.return" = "pallet.purple"
"syntax.keyword.storage" = "pallet.aqua"
"syntax.keyword.type" = "pallet.aqua"
"syntax.conditional" = "pallet.purple"
"syntax.repeat" = "pallet.purple"
"syntax.debug" = "pallet.purple"
"syntax.include" = "pallet.purple"
"syntax.exception" = "pallet.purple"
"syntax.type.definition" = "pallet.aqua"
"syntax.type.qualifier" = "pallet.aqua"
"syntax.storageclass" = "pallet.aqua"
"syntax.field" = "pallet.blue-light"
"syntax.variable.member" = "pallet.blue-light"
"syntax.variable.parameter" = "pallet.blue-light"
"syntax.variable.parameter.builtin" = "pallet.blue-light"
"syntax.constant.macro" = "pallet.purple"
"syntax.markup" = "pallet.foreground"
"syntax.markup.strong" = "pallet.aqua"
"syntax.markup.italic" = "pallet.purple"
"syntax.markup.underline" = "pallet.orange"
"syntax.markup.strikethrough" = "pallet.green"
"syntax.markup.heading" = "pallet.purple"
"syntax.markup.heading.1" = "pallet.purple"
"syntax.markup.heading.2" = "pallet.purple"
"syntax.markup.heading.3" = "pallet.purple"
"syntax.markup.heading.4" = "pallet.purple"
"syntax.markup.heading.5" = "pallet.purple"
"syntax.markup.heading.6" = "pallet.purple"
"syntax.markup.raw" = "pallet.orange"
"syntax.markup.raw.block" = "pallet.orange"
"syntax.markup.math" = "pallet.purple"
"syntax.markup.environment" = "pallet.purple"
"syntax.markup.environment.name" = "pallet.aqua"
"syntax.markup.link" = "pallet.orange"
"syntax.markup.link.url" = "pallet.orange"
"syntax.markup.link.label" = "pallet.blue-light"
"syntax.markup.list" = "pallet.foreground"
"syntax.markup.list.checked" = "pallet.aqua"
"syntax.markup.list.unchecked" = "pallet.green"
"syntax.markup.quote" = "pallet.green"
"syntax.comment.todo" = "pallet.yellow"
"syntax.comment.note" = "pallet.purple"
"syntax.comment.warning" = "pallet.orange"
"syntax.comment.error" = "pallet.purple"
"syntax.diff.plus" = "pallet.aqua"
"syntax.diff.minus" = "pallet.red"
"syntax.diff.delta" = "pallet.orange"
"syntax.namespace" = "pallet.aqua"
"syntax.symbol" = "pallet.blue-light"
"syntax.text" = "pallet.foreground"
"syntax.text.strong" = "pallet.aqua"
"syntax.text.emphasis" = "pallet.purple"
"syntax.text.underline" = "pallet.orange"
"syntax.text.strike" = "pallet.green"
"syntax.text.title" = "pallet.purple"
"syntax.text.literal" = "pallet.orange"
"syntax.text.uri" = "pallet.orange"
"syntax.text.math" = "pallet.purple"
"syntax.text.environment" = "pallet.purple"
"syntax.text.environment.name" = "pallet.aqua"
"syntax.text.reference" = "pallet.blue-light"
"syntax.text.todo" = "pallet.yellow"
"syntax.text.todo.checked" = "pallet.aqua"
"syntax.text.todo.unchecked" = "pallet.green"
"syntax.text.note" = "pallet.purple"
"syntax.text.note.comment" = "pallet.purple"
"syntax.text.warning" = "pallet.orange"
"syntax.text.danger" = "pallet.purple"
"syntax.text.danger.comment" = "pallet.purple"
"syntax.text.diff.add" = "pallet.aqua"
"syntax.text.diff.delete" = "pallet.red"
"syntax.tag" = "pallet.purple"
"syntax.tag.builtin" = "pallet.purple"
"syntax.tag.attribute" = "pallet.blue-light"
"syntax.tag.delimiter" = "pallet.foreground"
"syntax.punctuation" = "pallet.foreground"
"syntax.macro" = "pallet.purple"
"syntax.structure" = "pallet.aqua"
"syntax.lsp.type.class" = "pallet.aqua"
"syntax.lsp.type.comment" = "pallet.green"
"syntax.lsp.type.decorator" = "pallet.purple"
"syntax.lsp.type.enum" = "pallet.aqua"
"syntax.lsp.type.enumMember" = "pallet.blue"
"syntax.lsp.type.function" = "pallet.yellow"
"syntax.lsp.type.interface" = "pallet.aqua"
"syntax.lsp.type.macro" = "pallet.purple"
"syntax.lsp.type.method" = "pallet.yellow"
"syntax.lsp.type.modifier.java" = "pallet.purple"
"syntax.lsp.type.namespace" = "pallet.aqua"
"syntax.lsp.type.parameter" = "pallet.blue-light"
"syntax.lsp.type.property" = "pallet.blue-light"
"syntax.lsp.type.struct" = "pallet.aqua"
"syntax.lsp.type.type" = "pallet.aqua"
"syntax.lsp.type.typeParameter" = "pallet.aqua"
"syntax.lsp.type.variable" = "pallet.blue-light"
