[package]
name = "editor-git"

[package.edition]
workspace = true

[package.version]
workspace = true

[package.license]
workspace = true

[package.rust-version]
workspace = true

[dependencies]

[dependencies.editor-jobs]
path = "../editor-jobs"

[dependencies.editor-plugin-api]
path = "../../user/sdk"

[lib]
path = "src/lib.rs"
name = "editor_git"
required-features = []
crate-type = ["lib"]

[lints]
workspace = true
