[package]
name = "editor-plugin-api"

[package.edition]
workspace = true

[package.version]
workspace = true

[package.license]
workspace = true

[package.rust-version]
workspace = true

[dependencies]
abi_stable = "0.11"
serde_json = "1.0.149"

[dependencies.editor-buffer]
path = "../../crates/editor-buffer"

[dependencies.editor-core]
path = "../../crates/editor-core"

[dependencies.editor-dap]
path = "../../crates/editor-dap"

[dependencies.editor-fs]
path = "../../crates/editor-fs"

[dependencies.editor-git]
path = "../../crates/editor-git"

[dependencies.editor-icons]
path = "../../crates/editor-icons"

[dependencies.editor-lsp]
path = "../../crates/editor-lsp"

[dependencies.editor-syntax]
path = "../../crates/editor-syntax"

[dependencies.editor-theme]
path = "../../crates/editor-theme"

[lib]
path = "src/lib.rs"
name = "editor_plugin_api"
required-features = []
crate-type = ["lib"]
