[package]
name = "editor-render"

[package.edition]
workspace = true

[package.version]
workspace = true

[package.license]
workspace = true

[package.rust-version]
workspace = true

[dependencies]
ttf-parser = "0.21.1"

[lib]
path = "src/lib.rs"
name = "editor_render"
required-features = []
crate-type = ["lib"]
