[package]
name = "editor-terminal"

[package.edition]
workspace = true

[package.version]
workspace = true

[package.license]
workspace = true

[package.rust-version]
workspace = true

[dependencies.alacritty_terminal]
version = "0.25.1"
git = "https://github.com/zed-industries/alacritty"
rev = "9d9640d4"

[dependencies.editor-jobs]
path = "../editor-jobs"

[lib]
path = "src/lib.rs"
name = "editor_terminal"
required-features = []
crate-type = ["lib"]
