[package]
name = "volt-user"
build = "build.rs"

[package.edition]
workspace = true

[package.version]
workspace = true

[package.license]
workspace = true

[package.rust-version]
workspace = true

[dependencies]
abi_stable = "0.11"
serde_yaml = "0.9"
toml = "0.8.23"

[dependencies.editor-plugin-api]
path = "sdk"

[dependencies.serde]
version = "1.0.228"
features = ["derive"]

[lib]
path = "lib.rs"
name = "user"
required-features = []
crate-type = ["cdylib", "rlib"]
